server.port=9090
spring.cloud.config.enabled=false

gestopago.auth.url=https://gestopago.portalventas.net
gestopago.auth.id-distribuidor=83
gestopago.auth.codigo-dispositivo=GPS83-TPV-17
gestopago.auth.password=12345678
gestopago.service.url=https://gestopago.portalventas.net

spring.datasource.url=jdbc:postgresql://localhost:5434/prueba_db
spring.datasource.username=manuel
spring.datasource.password=linux123

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a8d3e691238914b1b3bc294c6534927a
jwt.expiration=3600000
jwt.refresh-expiration=86400000
